name: Create New Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest # Using the latest macOS runner which includes the latest Xcode
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Update to the latest version of checkout action

      - name: Install dependencies (packages)
        run: |
          curl -LO https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_macosx_x86_64
          sudo install -m755 ldid_macosx_x86_64 /usr/local/bin/ldid
          brew install 7zip gnu-sed

      - name: Compile f
        run: | 
          mkdir upload
          make package SCHEME="'feather (Release)'"
          mv packages/* upload/

      - name: Get Version Number
        id: get_version
        run: |
          # Assuming the path to Info.plist remains the same
          VERSION=$( /usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" Payload/feather.app/Info.plist )
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Setup
        run: |
          mv upload/feather.ipa upload/feather_v${VERSION}.ipa
          cp upload/feather_v${VERSION}.ipa upload/feather_v${VERSION}.tipa

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Feather v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          files: |
            upload/*ipa
          generate_release_notes: true
          fail_on_unmatched_files: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Corrected to use secrets.GITHUB_TOKEN